=== ks-no/fiks-arkiv-client-dotnet/KS.Fiks.IO.Arkiv.Client/Schema/sok.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.ks.no/standarder/fiks/arkiv/sok/v1"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.ks.no/standarder/fiks/arkiv/sok/v1" elementFormDefault="qualified">

    <xs:element name="sok" type="sok"/>
    <xs:complexType name="sok">
        <xs:sequence>
            <xs:element name="system" type="xs:string"/>
            <xs:element name="meldingId" type="xs:string"/>
            <xs:element name="tidspunkt" type="xs:dateTime"/>
            <xs:element name="take" type="xs:int"/>
            <xs:element name="skip" type="xs:int"/>
            <xs:element name="respons" type="respons"/>
            <xs:element name="parameter" type="parameter" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="responsType" type="responsType" minOccurs="1" maxOccurs="1" default="minimum"/>
            <xs:element name="inkluder" type="inkluder" minOccurs="0" maxOccurs="1"/>
            <xs:element name="sortering" type="sortering" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parameter">
        <xs:sequence>
            <xs:element name="felt" type="sokFelt"/>
            <xs:element name="operator" type="operatorType"/>
            <xs:element name="parameterverdier" type="parameterverdier" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parameterverdier">
        <xs:choice minOccurs="0" maxOccurs="1">
            <xs:element name="stringvalues" type="stringvalues"/>
            <xs:element name="datevalues" type="datevalues"/>
            <xs:element name="intvalues" type="intvalues"/>
            <xs:element name="eksternId" type="eksternId"/>
            <xs:element name="klassifikasjonvalues" type="klassifikasjonvalues"/>
            <xs:element name="virksomhetsspesifikkemetadata" type="vsmetadata"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="stringvalues">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="datevalues">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="value" type="xs:dateTime"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="intvalues">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="value" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="klassifikasjonvalues">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="klassifikasjonssystem" type="xs:string" minOccurs="0"/>
            <xs:element name="klasse" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="vsmetadata">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="key" type="xs:string" minOccurs="0"/>
            <xs:element name="value" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="eksternId">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="system" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="operatorType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="equal"/>
            <xs:enumeration value="notequal"/>
            <xs:enumeration value="between"/>
            <xs:enumeration value="lessthan"/>
            <xs:enumeration value="lessequal"/>
            <xs:enumeration value="greaterthan"/>
            <xs:enumeration value="greaterequal"/>
            <xs:enumeration value="inlist"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sokFelt">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sak.saksdato"/>
            <xs:enumeration value="sak.saksaar"/>
            <xs:enumeration value="sak.saksekvensnummer"/>
            <xs:enumeration value="sak.saksstatus"/>
            <xs:enumeration value="sak.administrativenhet"/>
            
            <!-- De påfølgende feltene bør diskuteres om vi trenger-->
            <xs:enumeration value="sak.matrikkelnummer.kommunenummer"/>
            <xs:enumeration value="sak.matrikkelnummer.gaardsnummer"/>
            <xs:enumeration value="sak.matrikkelnummer.bruksnummer"/>
            <xs:enumeration value="sak.planident.stat.landkode"/>
            <xs:enumeration value="sak.planident.fylke.fylkesnummer"/>
            <xs:enumeration value="sak.planident.kommune.kommunenummer"/>
            <!-- Slutt felter til diskusjon-->

            <xs:enumeration value="journalpost.journalaar"/>
            <xs:enumeration value="journalpost.journalsekvensnummer"/>
            <xs:enumeration value="journalpost.saksaar"/>
            <xs:enumeration value="journalpost.sakssekvensnummer"/>
            <xs:enumeration value="journalpost.journalpostnummer"/>
            <xs:enumeration value="journalpost.journalposttype"/>
            <xs:enumeration value="journalpost.journalstatus"/>
            <xs:enumeration value="journalpost.journaldato"/>
            <xs:enumeration value="journalpost.dokumentetsdato"/>
            <xs:enumeration value="dokumentbeskrivelse.opprettetDato"/>
            <xs:enumeration value="dokumentbeskrivelse.dokumenttype"/>
            <xs:enumeration value="dokumentbeskrivelse.dokumentstatus"/>

        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="respons">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mappe"/>
            <xs:enumeration value="saksmappe"/>
            <xs:enumeration value="registrering"/>
            <xs:enumeration value="journalpost"/>
            <xs:enumeration value="dokumentbeskrivelse"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="responsType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="noekler"/>
            <xs:enumeration value="minimum"/>
            <xs:enumeration value="utvidet"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="inkluder">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mappe"/>
            <xs:enumeration value="registrering"/>
            <xs:enumeration value="klasse"/>
            <xs:enumeration value="noekkelord"/>
            <xs:enumeration value="kryssreferanse"/>
            <xs:enumeration value="part"/>
            <xs:enumeration value="merknad"/>
            <xs:enumeration value="presedens"/>
            <xs:enumeration value="moetedeltaker"/>
            <xs:enumeration value="dokumentbeskrivelse"/>
            <xs:enumeration value="korrespondansepart"/>
            <xs:enumeration value="avskrivning"/>
            <xs:enumeration value="dokumentflyt"/>
            <xs:enumeration value="dokumentobjekt"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="sortering">
        <xs:sequence>
            <xs:element name="felt" type="sorteringFelt" minOccurs="1" maxOccurs="1"/>
            <xs:element name="type" type="sorteringType" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="sorteringType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="synkende"/>
            <xs:enumeration value="stigende"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sorteringFelt">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mappe.opprettetDato"/>
            <xs:enumeration value="mappe.avsluttetDato"/>
            <xs:enumeration value="mappe.referansearkivdel"/>

            <xs:enumeration value="sak.saksdato"/>
            <xs:enumeration value="sak.saksaar"/>
            <xs:enumeration value="sak.saksekvensnummer"/>
            <xs:enumeration value="sak.saksstatus"/>
            <xs:enumeration value="sak.administrativenhet"/>
            <xs:enumeration value="sak.saksansvarlig"/>

            <xs:enumeration value="registrering.opprettetDato"/>
            <xs:enumeration value="registrering.administrativenhet"/>
            <xs:enumeration value="registrering.journalpostansvarlig"/>

            <xs:enumeration value="journalpost.journalaar"/>
            <xs:enumeration value="journalpost.journalsekvensnummer"/>
            <xs:enumeration value="journalpost.saksaar"/>
            <xs:enumeration value="journalpost.sakssekvensnummer"/>
            <xs:enumeration value="journalpost.journalpostnummer"/>
            <xs:enumeration value="journalpost.journalposttype"/>
            <xs:enumeration value="journalpost.journalstatus"/>
            <xs:enumeration value="journalpost.journaldato"/>
            <xs:enumeration value="journalpost.dokumentetsdato"/>
            <xs:enumeration value="journalpost.forfallsdato"/>

            <xs:enumeration value="dokumentbeskrivelse.opprettetDato"/>
            <xs:enumeration value="dokumentbeskrivelse.dokumenttype"/>
            <xs:enumeration value="dokumentbeskrivelse.dokumentstatus"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== ks-no/fiks-arkiv-client-dotnet/KS.Fiks.IO.Arkiv.Client/Sample/Examples/Sok/sok_virksomhetsspesifikkemetadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<ar:sok xmlns:ar="http://www.arkivverket.no/standarder/noark5/sok"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.arkivverket.no/standarder/noark5/arkivmelding file:./sok.xsd">
    <ar:system>system0</ar:system>
    <ar:meldingId>meldingId0</ar:meldingId>
    <ar:tidspunkt>2006-05-04T18:13:51.0</ar:tidspunkt>
    <ar:take>10</ar:take>
    <ar:skip>10</ar:skip>
    <ar:respons>mappe</ar:respons>
    <ar:parameter>
        <ar:felt>mappe.virksomhetsspesifikkeMetadata</ar:felt>
        <ar:operator>equal</ar:operator>
        <ar:parameterverdier>
            <ar:virksomhetsspesifikkemetadata>
                <ar:key>Kaffetype</ar:key>
                <ar:value>Arabica</ar:value>
            </ar:virksomhetsspesifikkemetadata>
        </ar:parameterverdier>
    </ar:parameter>    
</ar:sok>

=== ks-no/fiks-arkiv-client-dotnet/KS.Fiks.IO.Arkiv.Client/Sample/Examples/Sok/sok_klassifikasjon_alternativ2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ar:sok xmlns:ar="http://www.arkivverket.no/standarder/noark5/sok"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.arkivverket.no/standarder/noark5/arkivmelding file:./sok.xsd">
    <ar:system>system0</ar:system>
    <ar:meldingId>meldingId0</ar:meldingId>
    <ar:tidspunkt>2006-05-04T18:13:51.0</ar:tidspunkt>
    <ar:take>10</ar:take>
    <ar:skip>10</ar:skip>
    <ar:respons>mappe</ar:respons>
    <ar:parameter>
        <ar:felt>sak.klassifikasjonssystem</ar:felt>
        <ar:operator>equal</ar:operator>
        <ar:parameterverdier>
            <ar:klassifikasjonvalues>
                <ar:klassifikasjonssystem>GBNR</ar:klassifikasjonssystem>
                <ar:klasse>21/400</ar:klasse>
            </ar:klassifikasjonvalues>
        </ar:parameterverdier>
    </ar:parameter>    
</ar:sok>

=== ks-no/fiks-arkiv-client-dotnet/KS.Fiks.IO.Arkiv.Client/Schema/Examples/sok.xml
<?xml version="1.0" encoding="UTF-8"?>
<ar:sok xmlns:ar="http://www.arkivverket.no/standarder/noark5/sok"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.arkivverket.no/standarder/noark5/arkivmelding file:./sok.xsd">
    <ar:system>system0</ar:system>
    <ar:meldingId>meldingId0</ar:meldingId>
    <ar:tidspunkt>2006-05-04T18:13:51.0</ar:tidspunkt>
    <ar:take>100</ar:take>
    <ar:skip>0</ar:skip>
    <ar:respons>mappe</ar:respons>
    <ar:parameter>
        <ar:felt>sakstittel</ar:felt>
        <ar:operator>inlist</ar:operator>
        <ar:parameterverdier>
            <ar:stringvalues>
                <ar:value>Test1</ar:value>
                <ar:value>Test2</ar:value>
                <ar:value>Test3</ar:value>
            </ar:stringvalues>
        </ar:parameterverdier>
    </ar:parameter>
</ar:sok>

=== ks-no/fiks-arkiv-client-dotnet/KS.Fiks.IO.Arkiv.Client/Schema/Examples/sok_jp.xml
<?xml version="1.0" encoding="UTF-8"?>
<ar:sok xmlns:ar="http://www.arkivverket.no/standarder/noark5/sok"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.arkivverket.no/standarder/noark5/arkivmelding file:./sok.xsd">
    <ar:system>system0</ar:system>
    <ar:meldingId>meldingId0</ar:meldingId>
    <ar:tidspunkt>2006-05-04T18:13:51.0</ar:tidspunkt>
    <ar:take>100</ar:take>
    <ar:skip>0</ar:skip>
    <ar:respons>journalpost</ar:respons>
    <ar:parameter>
        <ar:felt>registrering.tittel</ar:felt>
        <ar:operator>equal</ar:operator>
        <ar:parameterverdier>
            <ar:stringvalues>
                <ar:value>Kaffeavtale*</ar:value>
            </ar:stringvalues>
        </ar:parameterverdier>
    </ar:parameter>
    <ar:parameter>
        <ar:felt>journalpost.journalposttype</ar:felt>
        <ar:operator>equal</ar:operator>
        <ar:parameterverdier>
            <ar:stringvalues>
                <ar:value>I</ar:value>
            </ar:stringvalues>
        </ar:parameterverdier>
        </ar:parameter>
    <ar:parameter>
        <ar:felt>registrering.eksternId</ar:felt>
        <ar:operator>equal</ar:operator>
        <ar:parameterverdier>
            <ar:eksternId>
                <ar:system>SikriElements</ar:system>
                <ar:id>85295a5e-6415-410c-8a2c-5b368f1ed06c</ar:id>
            </ar:eksternId>
        </ar:parameterverdier>
    </ar:parameter>
    <ar:parameter>
        <ar:felt>journalpost.journaldato</ar:felt>
        <ar:operator>between</ar:operator>
        <ar:parameterverdier>
            <ar:datevalues>
                <ar:value>2006-05-04T18:13:51.0</ar:value>
                <ar:value>2016-05-04T18:13:51.0</ar:value>
            </ar:datevalues>
        </ar:parameterverdier>
    </ar:parameter>
</ar:sok>
